### PR TITLE
Create LOBE_HCPLS.py

### PR DESCRIPTION
**Pull request by akhanf**
Required for the LOBE study - copied from the tar2bids repo

### CODE REVIEW

**Comment by akhanf** [comment]
fyi I'm gonna force merge since this is a heuristic we've been using already in autobids-v1

**Comment by kaitj** [comment]
There is a bit of a delay on the autobids side since it is scheduled to only pull this repo once a day. Can manually run a `git pull` from the autobids vm instance if needed.

**Comment by akhanf** [comment]
if you're able to, that would be great! Trying to get the Khan^LOBE project working on v2 -- looks like I had a study set-up but inactive, though the dicom querying doesn't seem to be working - do you mind having a look at that too when you have a chance?

**Comment by kaitj** [comment]
Done - also set the heuristic for that study.

Is the dicom querying referring to the button on the autobids portal? It doesn't seem like `bidsdump` has access to `Khan^LOBE` on the dicom server (or any projects scanned under Khan^* for that matter), which may be why the querying isn't working. Tried `Khan^LOBE`, `Khan^*`, and `*^LOBE` - all came up empty.

**Comment by akhanf** [comment]
OK got it working now - bidsdump was listed to have access, but my guess is it was the bidsdump user identity before we migrated to a Western Service Identity for it, since removing and re-adding worked!

**Pull request merged**
